version: '3'

services:
  php7:
    image: php:7.4-fpm
    build:
      context: ./dockerFiles/php7
    hostname: php7
    ports:
      - "9001:9000"
    volumes:
      - ./project_files/:/var/www/html/
      - ./dockerFiles/php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    networks:
      app_net:
        ipv4_address: 162.15.228.10
    command: bash -c "cp /var/www/html/.env.example /var/www/html/.env && cd /var/www/html && composer install --ignore-platform-reqs &&  php artisan migrate:fresh --force --seed"

  nginx:
        platform: linux/x86_64
        image: nginx:1.13.8
        ports:
          - "80:80"
        volumes:
          - ./project_files/:/var/www/html/
          - ./dockerFiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          app_net:
            ipv4_address: 162.15.228.15
  mysql:
        platform: linux/x86_64
        image: mysql:8.0.28
        ports:
          - "3306:3306"
        networks:
          app_net:
            ipv4_address: 162.15.228.20
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:6.0
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 162.15.228.25

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 162.15.228.0/24
          gateway: 162.15.228.1